server:
  port: 8080
  servlet:
    contextPath: /walle
hibernate:
    generate_statistics: true
logging:
    file: /var/log/walle/walle.log
    level:
        com:
            indracompany:
                walle: info
            ucuenca:
                spring: info
        org:
            hibernate:
                SQL: info
            springframework: info
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
spring:
    datasource:
        dbcp2:
            initial-size: 1
            max-idle: 1
            max-total: 2
            max-wait: 11000
            min-idle: 0
            remove-abandoned: true
            remove-abandoned-timeout: 360
            test-on-borrow: true
            time-between-eviction-runs-millis: 60000
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${DB_PASSWORD:N9sdhpi2Dhn2}
        url: ${DB_URL:jdbc:mysql://172.31.8.161:3306/walle?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
        username: ${DB_USER:root}
    flyway:
        locations: classpath:db/migration
        enabled: ${FLYWAY_ENABLED:false}
    jackson:
        date-format: yyyy-MM-dd
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT-03:00
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
        show-sql: ${SHOW_SQL:false}
        hibernate:
          ddl-auto: update
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
springfox:
    documentation:
        swagger:
            v2:
                path: /api.json
walle:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:*}
  api-info:
      title: ${API_TITLE:Walle}
      description: ${API_DESCRIPTION:Documentação da API}
      version: ${API_VERSION:1.0.0}
      base-package: com.indracompany.walle.application
  security:
    oauth2:
      access-token:
        validity-seconds: ${OAUTH2_ACCESS_TOKEN_VALIDITY_SECONDS:1800}
      refresh-token:
        secure-cookie: ${OAUTH2_REFRESH_TOKEN_SECURE_COOKIE:true}
        validity-seconds: ${OAUTH2_REFRESH_TOKEN_VALIDITY_SECONDS:86400}
    jwt:
      signing-key: ${JWT_SIGNING_KEY:w@ll32019}
